use_frameworks!
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'BBTFoldLabel_Example' do
  pod 'BBTFoldLabel', :path => '../'

  target 'BBTFoldLabel_Tests' do
    inherit! :search_paths

    
  end
end
